/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "2.3.5.RELEASE"
    id("io.spring.dependency-management") version "1.0.10.RELEASE"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.3.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.3.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb:2.3.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-web:2.3.5.RELEASE")
    implementation("com.github.cloudyrock.mongock:mongock-bom:4.1.17")
    implementation("org.mongodb:mongodb-driver-sync:4.1.1")
    implementation("org.springframework.data:spring-data-mongodb:3.0.5.RELEASE")
    implementation("dev.galasa:com.auth0.jwt:3.8.1")
    implementation("org.springframework.hateoas:spring-hateoas:1.1.2.RELEASE")
    implementation("org.antlr:antlr4-runtime:4.8")
    implementation("commons-codec:commons-codec:1.15")
    implementation("javax.xml.bind:jaxb-api:2.3.0")
    implementation("com.github.cloudyrock.mongock:mongock-spring-v5:4.1.17")
    implementation("com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.17")
    implementation("io.springfox:springfox-boot-starter:3.0.0")
    implementation ("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation ("org.springframework.boot:spring-boot-starter-web")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.3.5.RELEASE")
}

springBoot {
    mainClassName = "dev.conductor.dataservices.DataServicesApplication"
}

group = "dev.conductor"
version = "0.0.1-SNAPSHOT"
description = "data-services"
java.sourceCompatibility = JavaVersion.VERSION_15
java.targetCompatibility = JavaVersion.VERSION_15

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
