export const issueConstants = {
  GET_SUCCESS: 'ISSUE_GET_SUCCESS',
  GET_FAILURE: 'ISSUE_GET_FAILURE',

  GET_COMMENTS_SUCCESS: 'ISSUE_GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'ISSUE_GET_COMMENTS_FAILURE',

  PUT_SUCCESS: 'ISSUE_PUT_SUCCESS',
  PUT_FAILURE: 'ISSUE_PUT_FAILURE',

  POST_SUCCESS: 'ISSUE_POST_SUCCESS',
  POST_FAILURE: 'ISSUE_POST_FAILURE'

}
