package dev.conductor.centra.application.controllers;

import dev.conductor.centra.domain.issue.dto.IssueDTO;
import dev.conductor.centra.domain.issue.entity.Issue;
import dev.conductor.centra.domain.project.entity.Project;
import dev.conductor.centra.domain.project.api.ProjectService;
import dev.conductor.centra.domain.search.api.SearchService;
import dev.conductor.centra.domain.search.cql.conditions.Condition;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

import dev.conductor.centra.domain.search.cql.ast.listener.CqlCustomListener;
import dev.conductor.centra.domain.search.cql.*;
import dev.conductor.centra.domain.search.cql.ast.*;
import dev.conductor.centra.domain.search.cql.ast.enumeration.*;
import dev.conductor.centra.domain.search.cql.cqlBaseListener;
import dev.conductor.centra.domain.search.cql.cqlParser;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CodePointCharStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/api/search")
public class SearchController {

    @Autowired
    private SearchService searchService;

    @Autowired
    private ProjectService projectService;

    //@Autowired
    //private ModelMapper modelMapper;

    @GetMapping
    public List<IssueDTO> searchByCql(@RequestParam String cql){
        //List<Condition> conditions = parser.parse(cql);
        //List<Condition> conditions = new ArrayList<>();

        /*if (conditions.size() == 0){
            throw new ResponseStatusException(
                    HttpStatus.UNPROCESSABLE_ENTITY,
                    "Search has no parameters"
            );
        }*/

        if (cql == null || cql.length() == 0) {
            throw new ResponseStatusException(
                    HttpStatus.UNPROCESSABLE_ENTITY,
                    "Empty cql string"
            );
        }

        CqlCustomListener listener = setup(cql);
        List<CqlStatement> statementList = listener.getStatementList();

        if (statementList.size() == 0) {
            throw new ResponseStatusException(
                    HttpStatus.UNPROCESSABLE_ENTITY,
                    "Сan't build criteria from this cql string"
            );
        }

        if (statementList.size() > 1) {
            throw new ResponseStatusException(
                    HttpStatus.UNPROCESSABLE_ENTITY,
                    "This cql string contains more than one cql statement. Please split it (parts are divided with semicolon)"
            );
        }

        // if we reached this line we know it's safe to retrieve via get(0)
        CqlStatement statement = statementList.get(0);

        final List<IssueDTO> dtoList = new ArrayList<>();

        // TODO I will continue translating AST into mongo-compatible query
        /*
        for (Issue issue: searchService.search(conditions)) {
            Project project = projectService.findById(issue.getProjectId());

            try {
                IssueDTO issueDTO = modelMapper.map(issue, IssueDTO.class);
                issueDTO.setProjectKey(project.getProjectKey());

                dtoList.add(issueDTO);
            } catch (RuntimeException e) {
                System.out.println(issue.getId() + " encountered an issue");
            }

        }*/

        // empty list so far
        return dtoList;
    }

    // I assume that classes generated by antlr aren't thread safe.
    // Hence need separate harness for each GET request
    private CqlCustomListener setup(String cqlString) {
        CodePointCharStream input = CharStreams.fromString(cqlString);
        cqlLexer lexer = new cqlLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        cqlParser parser = new cqlParser(tokens);
        ParseTree tree = parser.cql_stmt_list();

        ParseTreeWalker walker = new ParseTreeWalker();
        CqlCustomListener listener = new CqlCustomListener();
        walker.walk(listener, tree);
        return  listener;
    }
}
